services:

  app:
    build: .
    container_name: autotrade-admin-api-app
    depends_on:
      - db
    image: autotrade-admin-api-app:latest
    ports:
      - 8000:8000
    volumes:
      - source: .
        target: /autotrade-admin-api
        type: bind
    command: python manage.py migrate && python manage.py runserver

  db:
    container_name: autotrade-admin-api-db
    image: postgres:15.4
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    network_mode: "host" # remove if running the app container
