services:

  app:
    build: .
    container_name: autotrade-admin-api-app
    depends_on:
      - db
    image: autotrade-admin-api-app:latest
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - source: .
        target: /autotrade-admin-api
        type: bind

  db:
    container_name: autotrade-admin-api-db
    image: postgres:15.4
    restart: always
    env_file: .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
