# Generated by Django 5.0.1 on 2024-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
