name: ci-autotrade-admin-api

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

env:
  ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
  DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
  SALES_SERVICE_API_KEY: ${{secrets.SALES_SERVICE_API_KEY}}
  SALES_SERVICE_BASE_URL: ${{secrets.SALES_SERVICE_BASE_URL}}
  ADMIN_USER_EMAIL: ${{secrets.ADMIN_USER_EMAIL}}
  ADMIN_USER_PASSWORD: ${{secrets.ADMIN_USER_PASSWORD}}
  DEBUG: "False"
  POSTGRES_DB: "autotrade-admin-api-db"
  POSTGRES_USER: "postgres"
  ADMIN_USER_NAME: "admin"

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo apt-get update
      - run: sudo apt-get --no-install-recommends --no-upgrade -y install python3-pip
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=api --exitfirst
      - run: coverage report --fail-under=80
